spring:
  datasource:
    url: jdbc:postgresql://yangyufan.top:5433/toponym
    username: postgres
    password: 12345!@#$%
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  redis:
    database: 0
    host: yangyufan.top
    password: yang199691
    port: 6379
#   上传文件路径
file:
  upload:
    path: /data/file/